### ISSUE TITLE
Simplify CSS code for other shared properties.

### ISSUE THREAD

**Issue by josephtkim** [enikolasg/prj-rev-bwfs-dasmoto#7]
Great job applying the font-family property to multiple selectors in your CSS, which is a great way to simplify the code by making it concise. Try to simplify it further for all other shared properties. For instance,

```css
h1, h2, h3, p {
  font-family: Helvetica;
}

h1, h2, #price {
  font-weight: bold;
}

h1 {
  background-image: url("./images/pattern.jpg");
  font-size: 100px;
  text-align: center;
  color: khaki;
}

h2 {
  font-size: 32px;
  color: white;
}

#brushes {
  background-color: mediumspringgreen;
}

#frames {
  background-color: lightcoral;
}

#paint {
  background-color: skyblue;
}

#price {
  color: blue;
}
```
